<!DOCTYPE html>
<html>
<head>
    <title>${title}</title>
</head>
<body style="font-family: Arial; background-color: #f4f4f4;">

<div style="width: 600px; margin: 50px auto; background: white; padding: 20px; border-radius: 10px;">

    <h1>${movieName}</h1>

    <p><b>Year:</b> ${year}</p>
    <p><b>Genre:</b> ${genre}</p>

    <p>${description}</p>

    <h3> Rating: ${rating}</h3>

</div>

</body>
</html>
</html>